spring.application.name=HospitalJapa

# Dados da Conexao
spring.datasource.url=jdbc:postgresql://localhost:5436/hospital_db
spring.datasource.username=hospital
spring.datasource.password=hospital
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate/JPA
# "update" cria as tabelas automaticamente se elas nao existirem
# "create-drop" apaga tudo e cria as tabelas (bom pra dar reset)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect